version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3993:3993"
    env_file:
      - ./Backend/server.env
    depends_on:
      - postgres

  employee_payslip:
    build: ./Employee_Payslip
    ports:
      - "8888:80"

  hr_payslip:
    build: ./HR_Payslip
    ports:
      - "8889:80"

  postgres:
    image: postgres:15
    ports:
      - "5888:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

